const MALL_HEADER_AUTH = {
    /*
        页头:
        页尾:
        回到顶部按钮:
    */
    ROUTERS: [
        { value: '/mall/index' },
        { value: '/mall/favorites' },
        { value: '/mall/search' },
        { value: '/mall/all-articles' },
        { value: '/mall/all-deals' },
        { value: '/mall/deals-detail' },
        { value: '/mall/detail' },
        { value: '/mall/vehicle-list' },
        { value: '/mall/accessories-list' },
        { value: '/mall/peripheral-list' },
        { value: '/mall/promotional-list' },
        { value: '/mall/vehicle-list/detail' },
        { value: '/mall/accessories-list/detail' },
        { value: '/mall/peripheral-list/detail' },
        { value: '/mall/promotional-list/detail' },
        { value: '/mall/shopping-bag' },
        { value: '/preview/deals-preview' },
    ],
    FOOTER: [
        { value: '/mall/index' },
        { value: '/mall/favorites' },
        { value: '/mall/search' },
        { value: '/mall/all-articles' },
        { value: '/mall/all-deals' },
        { value: '/mall/deals-detail' },
        { value: '/mall/detail' },
        { value: '/mall/vehicle-list' },
        { value: '/mall/accessories-list' },
        { value: '/mall/peripheral-list' },
        { value: '/mall/promotional-list' },
        { value: '/mall/vehicle-list/detail' },
        { value: '/mall/accessories-list/detail' },
        { value: '/mall/peripheral-list/detail' },
        { value: '/mall/promotional-list/detail' },
        // { value: '/mall/shopping-bag' },
        { value: '/preview/deals-preview' },
    ],
    TOTOP: [
        { value: '/mall/index' },
        { value: '/mall/favorites' },
        { value: '/mall/search' },
        { value: '/mall/all-articles' },
        { value: '/mall/all-deals' },
        { value: '/mall/deals-detail' },
        { value: '/mall/detail' },
        { value: '/mall/vehicle-list' },
        { value: '/mall/accessories-list' },
        { value: '/mall/peripheral-list' },
        { value: '/mall/promotional-list' },
        { value: '/mall/vehicle-list/detail' },
        { value: '/mall/accessories-list/detail' },
        { value: '/mall/peripheral-list/detail' },
        { value: '/mall/promotional-list/detail' },
        { value: '/mall/shopping-bag' },
    ],
};
export default MALL_HEADER_AUTH;
