export default  {
    /*
        页头:
        页尾:
    */
    ROUTERS:[
        {value:'/mall/index'},
        {value:'/mall/favorites'},
        {value:'/mall/search'},
        {value:'/mall/all-articles'},
        {value:'/mall/all-deals'},
        {value:'/mall/detail'},
    ],
    FOOTER:[
        {value:'/mall/index'},
        {value:'/mall/favorites'},
        {value:'/mall/search'},
        {value:'/mall/all-articles'},
        {value:'/mall/all-deals'},
        {value:'/mall/detail'},
    ],
}